- hosts: localhost # change if using a seperate machine for building images
  become: True
  gather_facts: yes
  roles:
    # uncomment if using a seperate machine for building images
    # - {
    #     role: base,
    #     configure_firewall: 'true'
    #   }
    # - {
    #     role: docker
    #   }
    # - {
    #     role: geerlingguy.ntp,
    #     ntp_manage_config: true,
    #     ntp_servers: [
    #       0.de.pool.ntp.org,
    #       1.de.pool.ntp.org,
    #       2.de.pool.ntp.org,
    #       3.de.pool.ntp.org
    #     ]
    #   }
    - {
        role : toni.buildimages
      }
  vars:
    images:
      - { namespace: "registry.toni-media.de", name: "openresty_base", tag: "1.19.3.1", basenamespace: "", basename: "alpine", basetag: "3.13" }
      - { namespace: "registry.toni-media.de", name: "openresty_base_fat", tag: "1.19.3.1-alpine-fat", basenamespace: "", basename: "openresty_base", basetag: "1.19.3.1" }
      - { namespace: "registry.toni-media.de", name: "openresty", tag: "1.19.3.1-alpine-fat", basenamespace: "", basename: "openresty_base_fat", basetag: "1.19.3.1-alpine-fat" }
      - { namespace: "registry.toni-media.de", name: "sshd", tag: "3.13", basenamespace: "", basename: "alpine", basetag: "3.13" }